<a href="https://colab.research.google.com/github/deesha74/Machine-Learning/blob/main/Comparison_of_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How to evaluate multiple different machine learning algorithms on a dataset in Python with scikit-learn?

In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/csv_result-PhishingData.csv')
data.head()

id  SFH  popUpWidnow  ...  age_of_domain  having_IP_Address  Result
0   1    1           -1  ...              1                  0       0
1   2   -1           -1  ...              1                  1       1
2   3    1           -1  ...              1                  0       1
3   4    1            0  ...              1                  0       0
4   5   -1           -1  ...              1                  0       1

[5 rows x 11 columns]

In [ ]:
data.head()

id  SFH  popUpWidnow  ...  age_of_domain  having_IP_Address  Result
0   1    1           -1  ...              1                  0       0
1   2   -1           -1  ...              1                  1       1
2   3    1           -1  ...              1                  0       1
3   4    1            0  ...              1                  0       0
4   5   -1           -1  ...              1                  0       1

[5 rows x 11 columns]

In [ ]:
#we dont need id
X = data.iloc[:,1:-1]
X = X.values
Y = data.iloc[:,-1].values

In [ ]:
print(X)

[[ 1 -1  1 ...  1  1  0]
 [-1 -1 -1 ...  1  1  1]
 [ 1 -1  0 ... -1  1  0]
 ...
 [-1  0 -1 ... -1 -1  0]
 [ 0  0  1 ... -1  1  0]
 [ 1  0  1 ... -1 -1  0]]


In [ ]:
print(Y)

[ 0  1  1 ...  1  1 -1]


Normalizing the data

In [ ]:
from sklearn import preprocessing
X1 = preprocessing.normalize(X)

In [ ]:
print(X1)

[[ 0.35355339 -0.35355339  0.35355339 ...  0.35355339  0.35355339
   0.        ]
 [-0.35355339 -0.35355339 -0.35355339 ...  0.35355339  0.35355339
   0.35355339]
 [ 0.4472136  -0.4472136   0.         ... -0.4472136   0.4472136
   0.        ]
 ...
 [-0.40824829  0.         -0.40824829 ... -0.40824829 -0.40824829
   0.        ]
 [ 0.          0.          0.57735027 ... -0.57735027  0.57735027
   0.        ]
 [ 0.40824829  0.          0.40824829 ... -0.40824829 -0.40824829
   0.        ]]


Splitting of dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X1, Y, test_size = 0.25, random_state = 42)

In [ ]:
print(X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)

(1014, 9) (1014,) (339, 9) (339,)


# Linear Regression

Linear Regression is a regression model, it takes input and gives a continous output.
It is a statistical model. We use Linear regression to to predict the relationship between two variables. We plot the points and draw a straight line, also called regression line which is best fit for the scatter plot so that it can also predict for new features.

In linear regression we find the best fit line for the equation, predictive function:
y=mx+c

h(θ) = θ0 + θ1x1 + θ2x2 + ...

where, h(θ) is predicted output, θ is coefficient, and x1,x2,x3... are the features

Where we optimize m and c using gradient decent to reduce the Mean Squared Error.

In Linear regression we use ***Mean Squared Error*** as the metric loss.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
regr=linear_model.LinearRegression()
regr.fit(X_train, Y_train)
y_pred = regr.predict(X_test)
mean_squared_error(Y_test, y_pred)
r2_score(Y_test, y_pred)

0.643897461318726

Mean Squared Error for Linear Regression

In [ ]:
mean_squared_error(Y_test, y_pred)

0.32074978449522734

r2_score for linear regression

In [ ]:
r2_score(Y_test, y_pred)

0.643897461318726

# Logistic Regression

Logistic Regression is a classification model. It is used to assign observations to a discrete set of class, i.e., output lable is discrete in logistic regression. It is a probabilistic model.

Logistic regression uses an activation function called the ***Sigmoid Function*** .

Output in logistic regression is (0 <= x <= 1).
Sigmoid functions limits the cost function between 0 and 1.
Predictive function for Logistic Regression is: y^ = c1x1 + c2x2 + c3x3 + b

where c1,c2,c3 are coefficient, x1,x2,x3 are features and b is bias.

Here we can not use mean squared error as the cost function, so we use ***Cross Entropy*** also called log loss instead.

J = -y (log(y^)) , for y = 1

J = -(1-y) (log(1-y^)) , for y = 0

In [ ]:
from sklearn.linear_model import LogisticRegression
reg = linear_model.LogisticRegression()
reg.fit(X_train, Y_train)
y_pred = reg.predict(X_test)
from sklearn import metrics
metrics.accuracy_score(Y_test, y_pred)*100

83.77581120943954

# Naive Bayes

Naive Bayes is a collection of classification algorithm based on ***Bayes Theorem***.  Every pair of features being classified is independent of each other.

In Gaussian Naive Bayes classifier, continuous values associated with each feature are assumed to be distributed according to a Gaussian distribution. A Gaussian distribution is also called Normal distribution. When plotted, it gives a bell shaped curve which is symmetric about the mean of the feature values

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
y_pred = gnb.predict(X_test)

In [ ]:
from sklearn import metrics
metrics.accuracy_score(Y_test, y_pred)*100

82.00589970501476

# KNN

K-nearest neighbors is a non-parametric method used for classification and regression. It works on real time computation.  

The basic concept of KNN is to explore the neighbors around and assume that the test datapoint to be similar to them and derive the output. To come up with prediction, we look for k neighbors.


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, Y_train)
y_pred = neigh.predict(X_test)
from sklearn import  metrics
metrics.accuracy_score(Y_test, y_pred)*100

87.90560471976401