<a href="https://colab.research.google.com/github/deesha74/Machine-Learning/blob/main/Simple_Python_Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1D ARRAY

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


2D ARRAY

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [3]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)


In [5]:
print(np.ones(3))

[1. 1. 1.]


In [6]:
print(np.ones([3,2]))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
print(np.zeros(3))

[0. 0. 0.]


In [8]:
print(np.zeros([3,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
